//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public System.Guid AttachmentID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.Guid> ParentGUID { get; set; }
        public string NewFileName { get; set; }
        public string OldFileName { get; set; }
        public string FilePathPrefix { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> FileContentLength { get; set; }
        public string FileContentType { get; set; }
        public Nullable<int> TableType { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
    }
}
