//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperateLog
    {
        public System.Guid LogID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string LogDescription { get; set; }
        public Nullable<int> LogRank { get; set; }
        public Nullable<int> LogSource { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> IsRead { get; set; }
        public string PageFullName { get; set; }
        public string LogIP { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
    }
}
