//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCall
    {
        public System.Guid CallId { get; set; }
        public string BedNo { get; set; }
        public string BellNo { get; set; }
        public System.DateTime CallTime { get; set; }
        public System.DateTime SendTime { get; set; }
        public string QueueName { get; set; }
        public int MessageCategory { get; set; }
        public int IsDispose { get; set; }
        public System.Guid DisposeUserId { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
    }
}
