//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCustomer
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> BedID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerGender { get; set; }
        public string CustomerWedlock { get; set; }
        public string BedNumber { get; set; }
        public string BedNumberName { get; set; }
        public Nullable<int> CustomerAge { get; set; }
        public string CustomerJG { get; set; }
        public Nullable<System.DateTime> CustomerBrith { get; set; }
        public string CustomerCompany { get; set; }
        public string CustomerCardID { get; set; }
        public Nullable<int> CustomerType_dic { get; set; }
        public string CustomerSBKH { get; set; }
        public string CustomerMZ { get; set; }
        public Nullable<int> CustomerWHCD_dic { get; set; }
        public string CustomerZW { get; set; }
        public Nullable<int> CustomerYLJSR { get; set; }
        public string CustomerZZDH { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerYYZT { get; set; }
        public string CustomerSFBS { get; set; }
        public Nullable<int> CustomerJZDQ_dic { get; set; }
        public string ResidentialAddress { get; set; }
        public string ResidentialCode { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentCode { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerSX { get; set; }
        public string CustomerXMPY { get; set; }
        public string CustomerZYBH { get; set; }
        public Nullable<System.DateTime> CustomerYYSJ { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> CustomerLYSJ { get; set; }
        public string CustomerLYYY { get; set; }
        public string CustomerYLBZ { get; set; }
        public string CustomerJJYW { get; set; }
        public string CustomerJJSW { get; set; }
        public Nullable<int> CustomerYSLX_dic { get; set; }
        public string CustomerYYBH { get; set; }
        public string CustomerSFWWYY { get; set; }
        public Nullable<int> CustomerHLMC_dic { get; set; }
        public string CustomerGSR { get; set; }
        public Nullable<System.DateTime> DiagnosticDate { get; set; }
        public string Describe { get; set; }
        public string CustomerNationality { get; set; }
        public string CustomerBirthAddress { get; set; }
        public string Contacts { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> OperatorUserID { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public string CustomerHeadImg { get; set; }
        public string CustomerZZMM { get; set; }
        public string CustomerJYCD { get; set; }
        public string CustomerDlrXm { get; set; }
        public string CustomerDlrTel { get; set; }
        public string CustomerDlrDz { get; set; }
        public string CustomerDlrGx { get; set; }
        public string CustomerDlrYb { get; set; }
        public string CustomerZjxy { get; set; }
        public string CustomerJjly { get; set; }
        public string CustomerLxrGx { get; set; }
        public string ContactTel { get; set; }
        public string ContactCode { get; set; }
        public string RuZhuYuanYin { get; set; }
        public string ShenQingRenQm { get; set; }
        public Nullable<System.DateTime> ShenQingTime { get; set; }
        public string YuanFangYiJian { get; set; }
        public string YuanFangQm { get; set; }
        public Nullable<System.DateTime> YuanFangQmTime { get; set; }
        public string TxjSr { get; set; }
        public string HjJwhName { get; set; }
        public Nullable<System.DateTime> RzTime { get; set; }
        public string DyDbrName { get; set; }
        public string DyDbrByLrGx { get; set; }
        public string DyDbrAddress { get; set; }
        public string DyDbrCode { get; set; }
        public string DyDbrTel { get; set; }
        public string DeDbrName { get; set; }
        public string DeDbrByLrGx { get; set; }
        public string DeDbrAddress { get; set; }
        public string DeDbrCode { get; set; }
        public string DeDbrTel { get; set; }
        public string TiJianNr { get; set; }
        public string TjJbrQm { get; set; }
        public Nullable<System.DateTime> TjQmTime { get; set; }
        public string HlPgFzr { get; set; }
        public Nullable<System.DateTime> HlPgTime { get; set; }
        public string ShenPiNr { get; set; }
        public string SpFzrQm { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public Nullable<int> Stage { get; set; }
        public string CustomerHJDQ_dic { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
        public Nullable<int> WelfareCentreType { get; set; }
        public string OrgMindUserId { get; set; }
    }
}
