//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDrugBasic
    {
        public System.Guid ID { get; set; }
        public string DrugName { get; set; }
        public Nullable<int> DrugType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> OperatorUserID { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
        public string Unit { get; set; }
        public string Norms { get; set; }
        public string NormsValue { get; set; }
        public string DType { get; set; }
        public string UnitValue { get; set; }
        public string UnitSum { get; set; }
        public string UnitSumValue { get; set; }
        public string Yrjc { get; set; }
        public string Ycsl { get; set; }
        public string YcslValue { get; set; }
        public Nullable<System.DateTime> Yxq { get; set; }
        public string Zjs { get; set; }
        public string ZjsValue { get; set; }
    }
}
