//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMessage
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> FromID { get; set; }
        public Nullable<System.Guid> ToID { get; set; }
        public string MessageTitle { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<int> IsReaded { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> OperatorUserID { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
    }
}
