//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNodesPad
    {
        public int NodeId { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
        public string NodeName { get; set; }
        public string NodePath { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<int> IsLeftNode { get; set; }
        public string NodeTarget { get; set; }
        public string NodeStyle { get; set; }
        public string NodeClassName { get; set; }
        public string NodeIconPath { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<int> IsSuper { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SheBeiType { get; set; }
        public Nullable<int> NodeBizType { get; set; }
        public Nullable<int> NodeUserType { get; set; }
    }
}
