//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrgTLJGCongYe
    {
        public System.Guid ID { get; set; }
        public System.Guid OrganizationId { get; set; }
        public Nullable<System.Guid> WelfareId { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> StaffGender { get; set; }
        public string EmployType { get; set; }
        public string SocialSecurity { get; set; }
        public string Profession { get; set; }
        public string WeiJi { get; set; }
        public string SheGong { get; set; }
        public string QiTa { get; set; }
        public string HgChiZheng { get; set; }
        public string HgXueLi { get; set; }
        public string HgNianLing { get; set; }
        public string HgRuZhiNian { get; set; }
        public string HgHuJi { get; set; }
        public string HouQin { get; set; }
        public Nullable<System.Guid> OperateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public string Phone { get; set; }
        public string AddressPlace { get; set; }
    }
}
