//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPaymentPlan
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> OperatorUserID { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> HgId { get; set; }
        public Nullable<System.DateTime> ServerStart { get; set; }
        public Nullable<System.DateTime> ServerEnd { get; set; }
        public string WeekOne { get; set; }
        public string WeekTwo { get; set; }
        public string WeekThree { get; set; }
        public string WeekFour { get; set; }
        public string WeekFive { get; set; }
        public string WeekSix { get; set; }
        public string WeekServer { get; set; }
        public string Evaluate { get; set; }
        public string EvaluateText { get; set; }
        public Nullable<System.Guid> EvaluateUserID { get; set; }
        public string ServerTime { get; set; }
    }
}
