//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTLJGCongYe
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> WelfareId { get; set; }
        public string RestHomeName { get; set; }
        public Nullable<int> CongYe { get; set; }
        public Nullable<int> DaZhuan { get; set; }
        public Nullable<int> GaoZhong { get; set; }
        public Nullable<int> ChuZhong { get; set; }
        public Nullable<int> PYShiYeHeTong { get; set; }
        public Nullable<int> PYRenShiDaiLi { get; set; }
        public Nullable<int> PYShiLaoDongHeTong { get; set; }
        public Nullable<int> PYLaoWuPaiQian { get; set; }
        public Nullable<int> PYTuiXiuPingYong { get; set; }
        public Nullable<int> PYQiTa { get; set; }
        public Nullable<int> GenderMan { get; set; }
        public Nullable<int> GenderWoman { get; set; }
        public Nullable<int> JiaoJin { get; set; }
        public Nullable<int> NoJiaoJin { get; set; }
        public Nullable<int> GZGuanLi { get; set; }
        public Nullable<int> GZWJXiaoJi { get; set; }
        public Nullable<int> GZWJYiSheng { get; set; }
        public Nullable<int> GZWJHuShi { get; set; }
        public Nullable<int> GZWJKangFuShi { get; set; }
        public Nullable<int> GZWJYingYangShi { get; set; }
        public Nullable<int> GZWJYaoJiShi { get; set; }
        public Nullable<int> GZWJShiLiShi { get; set; }
        public Nullable<int> GZSGXiaoJi { get; set; }
        public Nullable<int> GZSGChuJi { get; set; }
        public Nullable<int> GZSGZhongJi { get; set; }
        public Nullable<int> GZSGGuanLi { get; set; }
        public Nullable<int> GZSGZhuanZhi { get; set; }
        public Nullable<int> GZSGQiTa { get; set; }
        public Nullable<int> GZQTXiaoJi { get; set; }
        public Nullable<int> GZQTKuaiJi { get; set; }
        public Nullable<int> GZQTWangGuan { get; set; }
        public Nullable<int> HLXiaoJi { get; set; }
        public Nullable<int> HLCZJiShi { get; set; }
        public Nullable<int> HLCZGaJi { get; set; }
        public Nullable<int> HLCZZhongji { get; set; }
        public Nullable<int> HLCZChuJi { get; set; }
        public Nullable<int> HLCZShangGangZheng { get; set; }
        public Nullable<int> HLCZQiTa { get; set; }
        public Nullable<int> HLXLDaZhuan { get; set; }
        public Nullable<int> HLXLGaoZhong { get; set; }
        public Nullable<int> HLXLChuZhong { get; set; }
        public Nullable<int> HLXLXiaoXue { get; set; }
        public Nullable<int> HLAge0To35 { get; set; }
        public Nullable<int> HLAge35To49 { get; set; }
        public Nullable<int> HLAge50 { get; set; }
        public Nullable<int> HLRZ0To1 { get; set; }
        public Nullable<int> HLRZ1To3 { get; set; }
        public Nullable<int> HLRZ3To5 { get; set; }
        public Nullable<int> HLRZ5 { get; set; }
        public Nullable<int> HLHJBenShi { get; set; }
        public Nullable<int> HLHJWaiSheng { get; set; }
        public Nullable<int> HQXiaoJi { get; set; }
        public Nullable<int> HQChuShi { get; set; }
        public Nullable<int> HQShuiDianGong { get; set; }
        public Nullable<int> HQQiTa { get; set; }
        public string FuZePerson { get; set; }
        public string FuHePerson { get; set; }
        public string TianBiaoPerson { get; set; }
        public string LianXiDianHua { get; set; }
        public Nullable<System.DateTime> TianBiaoDate { get; set; }
        public Nullable<System.Guid> OperateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public string UserImg { get; set; }
    }
}
