//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNursingPerLedger
    {
        public Nullable<System.DateTime> NursingTimeStart { get; set; }
        public string NursingContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> OperatorUserID { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> WelfareCentreID { get; set; }
        public Nullable<int> LedgerType { get; set; }
        public Nullable<System.DateTime> NursingTimeEnd { get; set; }
        public Nullable<System.DateTime> SignIn { get; set; }
        public Nullable<System.DateTime> SignOut { get; set; }
        public Nullable<System.Guid> PaymentPlanId { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string CustomerName { get; set; }
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> HgID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string ServerTime { get; set; }
        public Nullable<int> EvaluateType { get; set; }
    }
}
